executors:
  node:
    docker:
      - image: circleci/node:lts

aliases:
  restore_cache_yarn: &restore_cache_yarn
    restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - yarn-cache-{{ checksum "yarn.lock" }}
        - yarn-cache-

  restore_cache_gatsby: &restore_cache_gatsby
    restore_cache:
      name: Restore Gatsby Caches
      keys:
        - v1-always-

  restore_cache_netlify: &restore_cache_netlify
    restore_cache:
      name: Restore Netlify Package Cache
      keys:
        - netlify-cache-{{ checksum "yarn.lock" }}
        - netlify-cache-

  install_node_modules: &install_node_modules
    run:
      name: Install dependencies
      command: yarn

  save_cache_yarn: &save_cache_yarn
    save_cache:
      name: Save NPM Package Cache
      key: yarn-cache-{{ checksum "yarn.lock" }}
      paths:
        - ./node_modules

  save_cache_gatsby: &save_cache_gatsby
    save_cache:
      name: Save Gatsby File Cache
      key: v1-always-{{ epoch }}
      paths:
        - ./public
        - ./.cache

  save_cache_netlify: &save_cache_netlify
    save_cache:
      name: Save Netlify CLI Cache
      key: netlify-cache-{{checksum "yarn.lock"}}
      paths:
        - ./node_modules

version: 2.1

jobs:
  test:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache_yarn
      - <<: *restore_cache_gatsby
      - <<: *install_node_modules
      - <<: *save_cache_yarn
      - <<: *save_cache_gatsby
      - run:
          name: Test
          command: yarn test

  build:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache_yarn
      - <<: *restore_cache_gatsby
      - <<: *install_node_modules
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: ./
          paths:
            - public

  deploy:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - <<: *restore_cache_netlify
      - <<: *install_node_modules
      - run:
          name: Install netlify-cli
          command: yarn install netlify-cli
      - <<: *save_cache_netlify
      - run:
          name: Deploy to Netlify
          command: npx netlify deploy --dir=./public -p

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
