executors:
  node:
    docker:
      - image: circleci/node:lts

aliases:
  restore_cache_yarn: &restore_cache_yarn
    restore_cache:
      name: Restore Yarn Caches
      keys:
        - yarn-cache-{{ checksum "yarn.lock" }}
        - yarn-cache-

  restore_cache_gatsby: &restore_cache_gatsby
    restore_cache:
      name: Restore Gatsby Caches
      keys:
        - v1-always-

  install_node_modules: &install_node_modules
    run:
      name: Install dependencies
      command: yarn

  save_cache_yarn: &save_cache_yarn
    save_cache:
      name: Save NPM package cache
      key: yarn-cache-{{ checksum "yarn.lock" }}
      paths:
        - ./node_modules

  save_cache_gatsby: &save_cache_gatsby
    save_cache:
      name: Save Gatsby file cache
      key: v1-always-{{ epoch }}
      paths:
        - ./public
        - ./.cache

version: 2.1

jobs:
  build:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache_yarn
      - <<: *restore_cache_gatsby
      - <<: *install_node_modules
      - run:
          name: Build
          command: yarn build
      - <<: *save_cache_gatsby
      - persist_to_workspace:
          root: ./
          paths:
            - public

  deploy:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - <<: *restore_cache_yarn
      - <<: *install_node_modules
      - run:
          name: Install netlify-cli
          command: sudo npm install -g --silent netlify-cli
      - run:
          name: Deploy to Netlify
          command: netlify deploy --dir=./public -p

  release:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache_yarn
      - <<: *install_node_modules
      - run: npx semantic-release

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      - release:
          requires:
            - deploy
          filters:
            branches:
              only: master
